[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["hardhat/=node_modules/hardhat/"]
fs_permissions = [{ access = "read-write", path = "./frontend/src/contracts" }]

[rpc_endpoints]
hoodi = "${HOODI_RPC_URL}"
localhost = "http://127.0.0.1:8545"

[etherscan]
hoodi = { key = "${ETHERSCAN_API_KEY}", chain = 560048, url = "https://hoodi.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
